# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems:
  #- jekyll-archives
  - jekyll-paginate
  #- jekyll-sitemap

paginate: 5
paginate_path: "/blog/page/:num/"
comments: true


# SEO settings
title: Mingpeiyu Zhang
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://zhangmpy.site
baseurl: ""
# baseurl: ""
# Author settings
author:
  name      : Minegpeiyu Zhang
  job       : Master student @ <a href="http://tue.nl">TU/e</a>
  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb     : /images/face.jpg
  email     : zmpyzmpy@gmail.com
  url       : http://zhangmpy.site
  github    : http://github.com/zmpyzmpy
  twitter   : http://twitter.com/zmpyzmpy
  facebook  : http://www.facebook.com/people/Mingpeiyu-Zhang/100007896783322
  linkedin  : http://linkedin.com/in/mingpeiyuzhang


# navbar pages
navbar:

  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog
  - slug: archives
    title: Archives
  - slug: about
    title: About

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


sass:
  sass_dir: _scss
  style: compressed # expanded
