# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems:
  #- jekyll-archives
  - jekyll-paginate
  #- jekyll-sitemap

paginate: 5
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Mingpeiyu Zhang
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://zhangmpy.site
baseurl: ""
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/zmpyzmpy/zmpyzmpy.github.io
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name      : Minegpeiyu Zhang
  job       : Master student @ <a href="http://tue.nl">TU/e</a>
  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb     : /images/face.jpg
  email     : zmpyzmpy@gmail.com
  url       : http://zhangmpy.site
  github    : http://github.com/zmpyzmpy
  twitter   : http://twitter.com/zmpyzmpy
  facebook  : http://www.facebook.com/people/Mingpeiyu-Zhang/100007896783322
  linkedin  : http://linkedin.com/in/mingpeiyuzhang

# navbar pages
navbar:

  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog
  - slug: archives
    title: Archives
  - slug: about
    title: About


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]



# jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/
