# SEO settings
title: Mingpeiyu Zhang
description: "Mingpeiyu Zhang's personal website."
keywords: "Jekyll, blog, web, computer science, data science, machine learning"
url: http://zhangmpy.top
baseurl: ""
# baseurl: ""
# Author settings
author:
  name      : Minegpeiyu Zhang
  job       : Algorithm Engineer @ <a href="https://www.guandata.com/">Guan Data</a>
  bio       : "Grounded solidly in the basics of computer science, data science and mathematics with rich experiences both theoretical and practical."
  # thumb     : /images/face.jpg
  email     : zmpyzmpy@gmail.com
  url       : http://zhangmpy.top
  github    : http://github.com/zmpyzmpy
  twitter   : http://twitter.com/zmpyzmpy
  facebook  : http://www.facebook.com/people/Mingpeiyu-Zhang/100007896783322
  linkedin  : http://linkedin.com/in/mingpeiyuzhang
  kaggle    : https://www.kaggle.com/mingpeiyu


# navbar pages
navbar:


  - slug: blog
    title: Blog
  - slug: year-archive
    title: Archives
  - slug: tags
    title: Tags
  - slug: about
    title: About

# Plugins
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock


markdown: kramdown
excerpt_separator: "<!-- more -->"
# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# Build settings
permalink   : /blog/:year/:title/
highlighter : rouge
paginate: 5
paginate_path: "/blog/page/:num/"
comments: true


sass:
  sass_dir: _scss
  style: compressed # expanded

tag_page_layout: tag_page
tag_page_dir: tag




