# SEO settings
title: Mingpeiyu Zhang
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://zhangmpy.site
baseurl: ""
# baseurl: ""
# Author settings
author:
  name      : Minegpeiyu Zhang
  job       : Master student @ <a href="http://tue.nl">TU/e</a>
  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb     : /images/face.jpg
  email     : zmpyzmpy@gmail.com
  url       : http://zhangmpy.site
  github    : http://github.com/zmpyzmpy
  twitter   : http://twitter.com/zmpyzmpy
  facebook  : http://www.facebook.com/people/Mingpeiyu-Zhang/100007896783322
  linkedin  : http://linkedin.com/in/mingpeiyuzhang


# navbar pages
navbar:


  - slug: blog
    title: Blog
  - slug: year-archive
    title: Archives
  - slug: categories
    title: Categories
  - slug: about
    title: About

# Plugins
gems:
  - jekyll-feed
  - jekyll-paginate
  #- jekyll-sitemap
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock

markdown: kramdown
excerpt_separator: "<!-- more -->"
# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# Build settings
permalink   : /blog/:year/:title/
highlighter : pygments
paginate: 5
paginate_path: "/blog/page/:num/"
comments: true


sass:
  sass_dir: _scss
  style: compressed # expanded



# jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/
